2018-10-31-16-11 [DubboClientReconnectTimer-thread-2] [com.alibaba.dubbo.remoting.transport.AbstractClient] [ERROR] -  [DUBBO] client reconnect to 192.168.88.128:20880 find error . url: dubbo://192.168.88.128:20880/cn.zhixiangyun.api.service.user.UserService?anyhost=true&application=consumer&check=false&codec=dubbo&default.check=false&default.timeout=6000&dubbo=2.5.5&generic=false&heartbeat=60000&interface=cn.zhixiangyun.api.service.user.UserService&methods=addUser,getUserList&pid=7340&revision=1.0.0&side=consumer&timestamp=1540965297725&version=1.0.0, dubbo version: 2.5.5, current host: 192.168.88.1
  com.alibaba.dubbo.remoting.RemotingException: client(url: dubbo://192.168.88.128:20880/cn.zhixiangyun.api.service.user.UserService?anyhost=true&application=consumer&check=false&codec=dubbo&default.check=false&default.timeout=6000&dubbo=2.5.5&generic=false&heartbeat=60000&interface=cn.zhixiangyun.api.service.user.UserService&methods=addUser,getUserList&pid=7340&revision=1.0.0&side=consumer&timestamp=1540965297725&version=1.0.0) failed to connect to server /192.168.88.128:20880, error message is:Connection refused: no further information
	at com.alibaba.dubbo.remoting.transport.netty.NettyClient.doConnect(NettyClient.java:124)
	at com.alibaba.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:268)
	at com.alibaba.dubbo.remoting.transport.AbstractClient$1.run(AbstractClient.java:157)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.connect(NioClientSocketPipelineSink.java:384)
	at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processSelectedKeys(NioClientSocketPipelineSink.java:354)
	at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:276)
	... 3 more
